#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 14 13:02:16 MSK 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=
